### ISSUE TITLE
execute failed

### ISSUE THREAD

**Issue by tenthousands** [wtwinlab/BlockchainDB#1]
On line 15 of file scripts/eth/gen_eth_config.sh , you create genesisDir but not genesisTemplate and when i run the file,it results in an error on line 18&19.Could you help to fix it ?
ps Can you tell me which software version you are using?

the part logs are as follows:
+ cd scripts/eth
+ . env.sh
++ WORKSPACE=/root/go/src/github.com/EinWTW/BlockchainDB
++ ETH_BIN=/root/go/src/github.com/ethereum/go-ethereum/build/bin
++ ETH_CONFIG=/root/go/src/github.com/EinWTW/BlockchainDB/config.eth
++ ETH_HOME=/root/go/src/github.com/EinWTW/BlockchainDB/storage/ethereum
++ ETH_DATA=/root/Data/eth
+ rm -rf '/root/Data/eth*'
+ genesisDir=/root/go/src/github.com/EinWTW/BlockchainDB/config.eth.1.4
+ genesisTemplate=/root/go/src/github.com/EinWTW/BlockchainDB/storage/ethereum/networks/CustomGenesis.template
+ mkdir -p /root/go/src/github.com/EinWTW/BlockchainDB/config.eth.1.4
+ echo '# This is custom genesis config template given about each shard'
This is custom genesis config template given about each shard
+ template=
make: *** [Makefile:31: ethnet] Error 1

**Comment by wtwinlab** [comment]
> On line 15 of file scripts/eth/gen_eth_config.sh , you create genesisDir but not genesisTemplate and when i run the file,it results in an error on line 18&19.Could you help to fix it ? ps Can you tell me which software version you are using?
> 
> the part logs are as follows:
> 
> * cd scripts/eth
> * . env.sh
>   ++ WORKSPACE=/root/go/src/github.com/EinWTW/BlockchainDB
>   ++ ETH_BIN=/root/go/src/github.com/ethereum/go-ethereum/build/bin
>   ++ ETH_CONFIG=/root/go/src/github.com/EinWTW/BlockchainDB/config.eth
>   ++ ETH_HOME=/root/go/src/github.com/EinWTW/BlockchainDB/storage/ethereum
>   ++ ETH_DATA=/root/Data/eth
> * rm -rf '/root/Data/eth*'
> * genesisDir=/root/go/src/github.com/EinWTW/BlockchainDB/config.eth.1.4
> * genesisTemplate=/root/go/src/github.com/EinWTW/BlockchainDB/storage/ethereum/networks/CustomGenesis.template
> * mkdir -p /root/go/src/github.com/EinWTW/BlockchainDB/config.eth.1.4
> * echo '# This is custom genesis config template given about each shard'
>   This is custom genesis config template given about each shard
> * template=
>   make: *** [Makefile:31: ethnet] Error 1

Hi Liang,

Thanks for your comment. You may check the software version and other env settings in this Dokerfile: https://github.com/wtwinlab/BlockchainDB/blob/main/docker/Dockerfile

However, I would suggest you to refer the full version of the implementation in our official repository: https://github.com/nusdbsystem/Hybrid-Blockchain-Database-Systems

Best,
Tianwen

**Comment by tenthousands** [comment]
Thanks!
